package com.mydomain.learningjc

class Info {
    val allIslands = listOf<String>("Alcatraz Island", "Revdar Island", "Priye Island", "Nkpokiti Island")
    val ratings = listOf<String>("4.8", "5.0", "4.5", "4.7")
    val numberOfRatings = listOf<String>("685", "1,254", "998", "145")
    val distance = listOf<String>("2-3 hours", "17-20 hours", "4-6 hours", "12-14 hours")
    val islandPics = listOf<Int>(R.drawable.island1, R.drawable.island2, R.drawable.island3, R.drawable.island4)
    val description = listOf<String>("Alcatraz Island, located in the heart of San Francisco Bay, is an iconic landmark with a rich history. Once a military fortress, it transformed into a notorious federal penitentiary from 1934 to 1963, housing infamous criminals like Al Capone. The island's isolation and turbulent waters made escape seemingly impossible, contributing to its \"Rock\" nickname. Abandoned in 1963, Alcatraz later became a symbol of resistance during the Native American occupation in 1969-1971. Today, it is a National Historic Landmark and popular tourist destination, showcasing the cell blocks, guard quarters, and the compelling tales of its storied past.", "Revdar Island, a mysterious haven tucked away in uncharted waters, captivates with its enigmatic charm. A sanctuary for seekers of the extraordinary, the isle is shrouded in an ever-present mist that veils its secrets. Legends speak of ethereal creatures roaming its lush forests, and the air hums with the energy of ancient magic. The architecture is an eclectic blend of forgotten civilizations, and ruins whisper tales of a forgotten past. Floating gardens and luminescent flora paint the landscape with otherworldly hues. Revdar Island beckons adventurers to uncover its hidden realms, promising a journey into the realms of fantasy and wonder.", "Priye Island emerges like a gem in an azure sea, a utopian retreat untouched by time. Golden beaches stretch along its perimeter, kissed by gentle waves that carry tales of distant lands. The island's heartbeat pulses through vibrant coral reefs, where iridescent marine life dances in a symphony of colors. Majestic cliffs adorned with cascading waterfalls guard its secrets, while lush jungles teem with exotic flora and fauna. Priye's inhabitants, harmoniously attuned to nature's rhythm, celebrate their unique traditions and folklore. A haven of serenity, Priye Island invites wanderers to embrace its tranquility and bask in the enchantment of an idyllic paradise.", "Nkpokiti Island emerges from the ocean like an emerald in a sapphire sea, a fantasy realm brimming with mystique. A tapestry of lush greenery blankets its undulating landscape, concealing hidden waterfalls that cascade into crystalline pools. Mysterious ruins, adorned with intricate carvings, whisper tales of a forgotten civilization. The island resonates with the melodic calls of exotic birds, and iridescent butterflies flit through vibrant wildflowers. Nkpokiti's vibrant market square buzzes with the energy of traders, offering curious artifacts and magical elixirs. Enchanted by the island's spell, visitors embark on a journey through its whimsical wonders, where every step reveals a new chapter in its captivating narrative.")
}
